---
- hosts: demo_machine
  pre_tasks:
    - name: Verify Ansible is greater than 2.8
      assert:
        that: "ansible_version.full is version_compare('2.8', '>=')"
        msg: >
          " You must update Ansible to at least 2.8."

    - name: Check for websites
      uri:
        url: "{{ item.url }}"
        body_format: json
        status_code: 200
        return_content: yes
        validate_certs: NO
        method: GET
      register: result
      until: result.status == 200
      retries: 5
      delay: 2
      with_items:
      - { url: 'https://hub.docker.com' }
      - { url: 'https://github.com' }

    - name: install PIP modules
      pip:
        name:
          - pyYAML
          - kubernetes
          - openshift
        extra_args: --user

    - name: Check if Kubectl is installed in current shell
      shell: |
        which kubectl
      register: kubectl_is_installed
      
    - name: Fail if kubectl not installed
      assert:
        that: "kubectl_is_installed.stdout != ''"
        fail_msg: "kubectl is not found in the current shell. Please install kubectl and connect it to your target cluster."
        success_msg: "kubectl found. Located at {{ kubectl_is_installed.stdout }}"
  
  tasks:
    - name: Get POD information for DAP instances
      k8s_facts:
        kind: pod
        namespace: dap
        label_selectors:
          - role = source
      register: dappod
      until: dappod.resources[0].status.containerStatuses[0].ready == true
      retries: 60
      delay: 2

    - name: Configure Variable with pod name
      set_fact:
        sourcePodName: "{{ dappod.resources[0].metadata.name }}"

