---
- hosts: demo_machine
  pre_tasks:
    - name: Verify Ansible is greater than 2.5
      assert:
        that: "ansible_version.full is version_compare('2.6', '>=')"
        msg: >
          " You must update Ansible to at least 2.6."
    # - name: Check for websites
    #   uri:
    #     url: "{{ item.url }}"
    #     body_format: json
    #     status_code: 200
    #     return_content: yes
    #     validate_certs: NO
    #     method: GET
    #   register: result
    #   until: result.status == 200
    #   retries: 5
    #   delay: 2
    #   with_items:
    #   - { url: 'https://hub.docker.com' }
    #   - { url: 'https://github.com' }
 
  vars_prompt:
  - name: "mode"
    prompt: 'Do you want to stand up a new environment or delete an existing environment? ("new" or "delete")'
    default: "new"
    private: no
  
  tasks:
    - include_tasks: dap.yml
      when: mode == 'new'
    
    - include_tasks: nginxIngress.yml
      when: mode == 'new'

    - k8s:
        state: absent
        src: "{{ playbook_dir }}/files/manifests/{{ item }}.yaml"
      with_items:
      - dapNamespaceManifest
      - nginxIngressKustomization
      when: mode == 'delete'
  
  vars:
    dapAdmin: 'admin'
    dapAdminPass: 'Cyberark1'
    dapAccount: 'cyberark'
    dapPort: '32525'
    dapMasterService: 'source.dap.svc.cluster.local'
    dapFollowerService: 'access.dap.svc.cluster.local'
    dapFollowerReplicaCount: 1
    dapMasterContainerName: 'node'
    demoMachineAddress: "{{ ansible_default_ipv4.address }}"