---
- name: Get POD information for DAP access instance
  k8s_facts:
    kind: pod
    namespace: dap
    label_selectors:
      - role = access
  register: dappod
  until: dappod.resources[0].status.containerStatuses[0].ready == true
  retries: 60
  delay: 2

- name: Configure Variable with pod name
  set_fact:
    accessPodName: "{{ dappod.resources[0].metadata.name }}"

- name: Check that access node is not already configured
  shell: |
    kubectl -n dap exec {{ accessPodName }} -i -- evoke role
  register: accessNode_configured

- name: Configure follower when DAP instance is not configured
  include_tasks: configureAccess.yml
  when: accessNode_configured.stdout == 'blank'