---
- name: Get POD information for DAP Access instances
  k8s_facts:
    kind: pod
    namespace: dap
    label_selectors:
      - role = access
  register: dappod
  until: dappod.resources[0].status.containerStatuses[0].ready == true
  retries: 5
  delay: 2

- name: Configure Variable with pod name
  set_fact:
    accessPodName: "{{ dappod.resources[0].metadata.name }}"

- name: Unpack seed
  shell: |
    kubectl exec -n dap {{ accessPodName }} -i -- evoke unpack seed /seed/seed.tar

- name: Configure Access node
  shell: |
    kubectl exec -n dap {{ accessPodName }} -i -- evoke configure follower