- !policy
  id: k8s-follower
  body:
  - !webservice
  
  - !layer
  
  # - !variable kubernetes/service-account-token
  
  # - !variable kubernetes/ca-cert
  
  # - !variable kubernetes/api-url
  
  - !variable ca/key
  
  - !variable ca/cert

  - !policy
    id: apps
    owner: !group /admins
    body:
    - !layer

    - &authenticated-resources-k8s
      - !host
        id: dap/service_account/conjur-cluster
        annotations:
          kubernetes/authentication-container-name: authenticator
          kubernetes: "true"

      - !host
        id: jenkins/*/*
        annotations:
          kubernetes/authentication-container-name: authenticator
          kubernetes: "true"

    - !grant
      role: !layer
      members: *authenticated-resources-k8s
      
  - !permit
    resource: !webservice
    privilege: [ read, authenticate ]
    role: !layer apps

- !policy
  id: okd-follower
  body:
  - !webservice
  
  - !layer
  
  - !variable kubernetes/service-account-token
  
  - !variable kubernetes/ca-cert
  
  - !variable kubernetes/api-url
  
  - !variable ca/key
  
  - !variable ca/cert

  - !policy
    id: apps
    owner: !group /admins
    body:
    - !layer

    - &authenticated-resources-okd
      - !host
        id: dap/service_account/conjur-cluster
        annotations:
          kubernetes/authentication-container-name: authenticator
          openshift: "true"
          
    - !grant
      role: !layer
      members: *authenticated-resources-okd
      
  - !permit
    resource: !webservice
    privilege: [ read, authenticate ]
    role: !layer apps