- !policy
  id: frontend
  body:
    - &frontendsecrets
      - !variable
        id: nginx_user
        
      - !variable
        id: nginx_pwd
        
      - !variable
        id: nginx_address
    
    - !permit
      role: !group /jenkins/full-access
      resource: *frontendsecrets
      privileges:
       - read
       - execute
       - update
       
    - !permit
      role: !group /jenkins/read-only
      resource: *frontendsecrets
      privileges:
       - execute
  
- !policy
  id: backend
  body:
    - &backendsecrets
      - !variable
        id: postgres_user
        
      - !variable
        id: postgres_pwd
      
      - !variable
        id: postgres_address
    
    - !permit
      role: !group /jenkins/full-access
      resource: *backendsecrets
      privileges:
       - read
       - update
       - execute
    
    - !permit
      role: !group /jenkins/read-only
      resource: *backendsecrets
      privileges:
       - execute