---
- !user mike

- !user john

- !user paul

- !user eva

- !group admins

- !group devops

- !grant
  role: !group admins
  members:
   - !user mike
   - !user eva

- !grant
  role: !group devops
  members:
   - !user john
   - !user paul
   - !group admins

- !permit
  role: !group admins
  privileges:
   - read
   - update
   - create
  resources:
   - !policy root

- !policy
  id: conjur/authn-k8s
  owner: !group /devops

- !policy
  id: conjur/seed-generation
  owner: !group /devops
  body:
   - !webservice

   - !layer consumers

   - !permit
     role: !layer consumers
     privilege: [ "execute" ]
     resource: !webservice

- !grant
  role: !layer conjur/seed-generation/consumers
  member: !host conjur/authn-k8s/k8s-follower/apps/dap/service_account/conjur-cluster
  
- !policy
  id: jenkins
  owner: !group /devops
  
- !policy
  id: resources
  owner: !group /devops