---
- name: Configure DAP 
  shell: |
    kubectl exec -n dap {{ sourcePodName }} -i -- evoke configure master -h {{ dapSourceService }} -p {{ dapAdminPass }} {{ dapAccount }}

- name: Wait for health page to report OK
  uri:
    url: "https://{{dapIngressRoute}}/health"
    return_content: yes
    body_format: json
    validate_certs: no
    method: GET
  register: results
  until: results.conjur_health == "OK"
  retries: 60
  delay: 2