---
- name: Get API token
  uri:
    url: https://{{dapIngressRoute}}/authn/{{ dapAccount }}/login
    return_content: yes
    method: GET
    url_password: "{{ dapAdminPass }}"
    url_username: "{{ dapAdmin }}"
    force_basic_auth: yes
    validate_certs: no
  register: dapAPIKey

- name: Get Authentication token
  uri:
    url: https://{{dapIngressRoute}}/authn/{{ dapAccount }}/{{ dapAdmin }}/authenticate
    return_content: yes
    method: POST
    body: "{{ dapAPIKey.content }}"
    validate_certs: no
  register: dapToken

- name: Generate dap JWT
  set_fact:
    dapTokenFormatted: "{{ dapToken.content | b64encode | replace('\r\n', '') }}"
  no_log: yes

- name: Load policies
  uri:
    url: https://{{dapIngressRoute}}/policies/{{ dapAccount }}/policy/{{ item }}
    status_code: 201
    return_content: yes
    method: PUT
    headers:
      Authorization: Token token="{{ dapTokenFormatted }}"
    validate_certs: no
    body: "{{lookup('file', '{{ role_path }}/files/policy/{{ item }}.yml') }}"
  with_items:
    - root
    - conjur/authn-k8s
    - jenkins
    - gitlab
    - resources