---
- name: Get POD information for DAP instances
  k8s_facts:
    kind: pod
    namespace: dap
    label_selectors:
      - role = source
  register: dappod
  until: dappod.resources[0].status.containerStatuses[0].ready == true
  retries: 60
  delay: 2

- name: Configure Variable with pod name
  set_fact:
    sourcePodName: "{{ dappod.resources[0].metadata.name }}"

- name: Check to see if DAP is running.
  uri:
    url: "https://{{dapIngressRoute}}/health"
    return_content: yes
    body_format: json
    validate_certs: no
    method: GET
    status_code: 200, 404, -1
  register: dapSourceConfig

- name: Configure Source node
  include_tasks: configureSource.yml
  when: dapSourceConfig.status == -1

- name: Load Policies
  include_tasks: loadPolicy.yml

# - name: Initialize Certificate
#   shell: |
#     kubectl -n dap exec {{ sourcePodName }} -i -- chpst -u conjur conjur-plugin-service possum rake authn_k8s:ca_init[“conjur/authn-k8s/{{item}}”]
#   with_items:
#     - k8s-follower
#     - okd-follower